version: "3"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chiefonboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: chiefonboarding/chiefonboarding:latest
    restart: always
    ports:
      - "172.17.0.1:8888:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chiefonboarding
      - ALLOWED_HOSTS=${DOMAIN}
      - ACCOUNT_EMAIL=${ACCOUNT_EMAIL}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - db
